## Numpy.part2

In [1]:
import numpy as np

## creation

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
# 실수도 가능
np.arange(0,1.4,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2])

## 그래프 그리는 경우

In [6]:
x= np.arange(-2,2.005,0.01)
x.size, x[-1]

(401, 2.0000000000000036)

In [7]:
x= np.linspace(-2,2,40) #(시작,끝, 등분)
x.size, x[-1]

(40, 2.0)

In [ ]:
import 

## ones, zeros, empty

In [8]:
np.ones(shape=(10), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((8,), np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [11]:
np.empty((4,))

array([0., 0., 0., 0.])

## something like

In [12]:
a = np.arange(12).reshape(3,4)
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 단위 행렬 - 정방형 행렬

In [15]:
np.identity(n=3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [17]:
np.identity(3).dtype

dtype('float64')

## eye. 대각선이 1인 행렬

In [18]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [19]:
np.eye(3,5,2,dtype=np.int16)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [22]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix), np.diag(matrix,k=1)

(array([0, 4, 8]), array([1, 5]))

In [21]:
np.diag(np.arange(9).reshape(3,3))

array([0, 4, 8])

### Random sampling

In [23]:
np.random.seed(seed=2021)
np.random.random()

0.6059782788074047

In [24]:
np.random.uniform(size=10) # 동일한 확률

array([0.73336936, 0.13894716, 0.31267308, 0.99724328, 0.12816238,
       0.17899311, 0.75292543, 0.66216051, 0.78431013, 0.0968944 ])

In [25]:
np.random.normal(size=10) # N(0,1) 평균 0 표준편차 1

array([-0.75051215,  0.21162099,  2.0448903 ,  1.07526774,  0.07902026,
        0.49328237, -0.79136747, -2.13059519,  0.31720629, -1.36461749])

In [ ]:
import matplotlib as plt
rand_norm = np.random.randn(1000)
plt.hist(rand_norm)
plt.show()

## 5. operation

In [29]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a.sum()

55

In [31]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a.sum()

78

In [33]:
# column의 합, row 방향
a.sum(axis=0)

array([15, 18, 21, 24])

In [34]:
a.sum(axis=1)

array([10, 26, 42])

In [36]:
b = np.arange(1,25).reshape(2,3,4)
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [38]:
b.sum(axis=0) # (2,3,4) -> (3,4)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [39]:
b.sum(axis=1) # (2,3,4) -> (2,4)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [40]:
b.sum(axis=2) # (2,3,4) -> (2,3)

array([[10, 26, 42],
       [58, 74, 90]])

### 통계, 수학함수

In [41]:
b.mean()

12.5

In [42]:
b.var()

47.916666666666664

In [44]:
b.std()

6.922186552431729

In [45]:
a.mean(), a.mean(axis=0), a.mean(axis=1)

(6.5, array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

In [47]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

### concatenate

In [57]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,7).reshape(1,2)
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
b.T

array([[5],
       [6]])