# 데이터프레임 클래스

## 데이터프레임 생성

In [1]:
import numpy as np
import pandas as pd

In [15]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [ ]:
df.T

In [3]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data,index=index, columns= columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [4]:
df.지역.values

array([ 0,  6, 12, 18])

In [5]:
df['2015'].values

array([ 1,  7, 13, 19])

In [6]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [16]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

### 열 데이터의 갱신, 추가, 삭제

In [17]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] *100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [18]:
df['2020'] = [5,6,7,8]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     5
부산  경상권  3448737  3393191  3512547  3655437           1.63     6
인천  수도권  2890451  2632035  2517680  2466338           9.82     7
대구  경상권  2466052  2431774  2456016  2473990           1.41     8

### 열 인덱싱

In [19]:
df['지역'] # 결과 Series

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [20]:
df[['지역','2015']] # 결과 DataFrame

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [21]:
df[['2010']]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [22]:
type(df[['2010']])

pandas.core.frame.DataFrame

### 행 인덱싱

In [25]:
df[:'서울'] # 행단위로 인덱싱 하기 위해서는 : 슬라이싱을 해야한다.

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     5

In [26]:
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     5
부산  경상권  3448737  3393191  3512547  3655437           1.63     6

In [23]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [24]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

### 개별 데이터 인덱싱
- df['열 이름']['행 이름']

In [27]:
df['2015']['서울']

9904312

In [28]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [29]:
df.수학

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [32]:
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [36]:
df['평균'] = round((df['국어']+df['영어'] + df['수학'])/3,1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [34]:
df['영어']['방자'] = 80
df

<ipython-input-34-6a80b0141b1b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['영어']['방자'] = 80


국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  46.666667

In [35]:
df.values

array([[80.        , 90.        , 90.        , 86.66666667],
       [90.        , 70.        , 60.        , 73.33333333],
       [70.        , 60.        , 80.        , 70.        ],
       [30.        , 80.        , 70.        , 46.66666667]])

In [ ]:
np.mean(df.values, axis=1)

In [38]:
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
del df['평균']

In [43]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  80  70

In [47]:
df.T[['춘향']]

춘향
국어  80
영어  90
수학  90

In [44]:
df.head(3).tail(2)

국어  영어  수학
몽룡  90  70  60
향단  70  60  80

In [48]:
df.T['향단']

국어    70
영어    60
수학    80
Name: 향단, dtype: int64