## numpy1

## Numerical Python(Numpy) - Part1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: x*3,a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## Numpy Dimensional array

In [5]:
a = np.array([1,3,5,7,9], float)
a

array([1., 3., 5., 7., 9.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape

(dtype('float64'), (5,))

## Array shape

In [8]:
# 1차원(vector)
vec = np.array([1,4,7,10])
vec.shape

(4,)

In [10]:
# matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
matrix

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
tensor.shape

(2, 3, 4)

In [13]:
# element를 모두 곱함
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [17]:
a = np.array([1,2,3], dtype = np.float32)
a

array([1., 2., 3.], dtype=float32)

In [18]:
b= np.array([2,3,4], dtype = np.int16)
b

array([2, 3, 4], dtype=int16)

### reshape

In [19]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
matrix.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
c= matrix.flatten()
c

array([1, 2, 3, 4, 5, 6])

## Indexing & Slicing

In [21]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
matrix[0][1]

2

In [23]:
matrix[0,1]

2

## Slicing

In [26]:
b= np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [28]:
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [29]:
b[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [30]:
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))